version: '3.7'

services:
  nginx:
    image: nginx-stable-alpine
    container_name: wp-wbs-nginx
    ports:
      - 8085:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
  mysql:
    image: mysql:latest
    container_name: wp-wbs-db
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html
